# Generated by Django 4.0.4 on 2022-06-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='images/Vehicles_pic')),
                ('category', models.CharField(choices=[('Jeep', 'jeep'), ('Minivan', 'minivan'), ('Truck', 'Truck'), ('Car', 'car')], default='Car', max_length=25)),
                ('year_of_making', models.DateTimeField(auto_now_add=True)),
                ('hourly_rental_price', models.IntegerField(choices=[(20, 20), (30, 30), (40, 40)], default=20)),
                ('location', models.CharField(help_text='The location of the vehicle', max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='users_app.usercredential')),
            ],
        ),
        migrations.CreateModel(
            name='Reviwes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=140)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_Reviwes', to='users_app.usercredential')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auther_Reviwes', to='users_app.usercredential')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Vehicle received date')),
                ('end_date', models.DateTimeField(help_text='Vehicle return date, at least 5 hours after vehicle received date')),
                ('vehicle_delivery', models.BooleanField(default=False, help_text='Does the rentee wants the vehicle delevered to them or not')),
                ('cost', models.DecimalField(decimal_places=2, help_text='The total cost of renting the vehicle for N hours + 20% of renting cost if the user wants the vehicle deliverd to them', max_digits=5)),
                ('approve', models.BooleanField(default=False)),
                ('rentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentee_Booking', to='users_app.usercredential')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_Booking', to='c2c_vehicle_rental_app.vehicle')),
            ],
        ),
    ]
