# Generated by Django 4.0.4 on 2022-06-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_vehicle_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='The total cost of renting the vehicle for N hours + 20% of renting cost if the user wants the vehicle deliverd to them', max_digits=7),
        ),
    ]
